"""Architect Agent – Senior Software Architect that analyzes PM output
and proposes a modern, scalable architecture with justifications."""

from __future__ import annotations

import asyncio
import json
import queue
import re
import threading
from typing import Optional

from langchain_core.messages import HumanMessage, SystemMessage
from pydantic import BaseModel, Field
from config.llm_config import llm_architect
from tools.llm_helpers import clean_llm_response, parse_llm_json

from agents.pm_agent import PMOutput


# ── Pydantic output models ──────────────────────────────────────────────────

class TechStack(BaseModel):
    frontend: str = Field(..., description="Frontend technology")
    backend: str = Field(..., description="Backend technology")
    database: str = Field(..., description="Database technology")
    infrastructure: str = Field(..., description="Infrastructure / deployment")
    additional_tools: list[str] = Field(
        ..., description="Additional tools and libraries"
    )


class APIEndpoint(BaseModel):
    method: str = Field(..., description="HTTP method: GET, POST, PUT, DELETE")
    path: str = Field(..., description="Endpoint path, e.g. /api/v1/users")
    description: str = Field(..., description="What this endpoint does")
    request_body: Optional[str] = Field(
        default=None, description="Request body schema description"
    )
    response: str = Field(..., description="Response schema description")


class DatabaseEntity(BaseModel):
    name: str = Field(..., description="Entity / table name")
    fields: list[str] = Field(..., description="List of field definitions")
    relationships: list[str] = Field(..., description="Relationships to other entities")


class ArchitectOutput(BaseModel):
    project_name: str = Field(..., description="Project name")
    architecture_pattern: str = Field(
        ...,
        description='Architecture pattern, e.g. "Clean Architecture", "MVC", "Microservices"',
    )
    tech_stack: TechStack = Field(..., description="Chosen technology stack")
    api_endpoints: list[APIEndpoint] = Field(..., description="API endpoint definitions")
    database_entities: list[DatabaseEntity] = Field(
        ..., description="Database entity definitions"
    )
    mermaid_diagram: str = Field(
        ..., description="Architecture diagram in valid Mermaid syntax"
    )
    key_decisions: list[str] = Field(
        ..., description="Key architectural decisions with justifications"
    )
    context7_enriched: bool = Field(
        default=False, description="Whether decisions were enriched by Context7"
    )


ARCHITECT_SYSTEM_PROMPT = """\
You are a Senior Software Architect with over 15 years of experience in mobile and backend system design.

Your task is to receive a project document with user stories (generated by a Product Manager) and propose a modern, scalable, and well-justified software architecture.

STRICT RULES:
1. Respond ONLY with a valid JSON. Do NOT include explanatory text, comments, or markdown code blocks (```).
2. The JSON must follow EXACTLY this schema:

{{
  "project_name": "string",
  "architecture_pattern": "string (e.g. Clean Architecture, MVC, Microservices)",
  "tech_stack": {{
    "frontend": "string",
    "backend": "string",
    "database": "string",
    "infrastructure": "string",
    "additional_tools": ["string"]
  }},
  "api_endpoints": [
    {{
      "method": "GET | POST | PUT | DELETE",
      "path": "/api/v1/resource",
      "description": "string",
      "request_body": "string or null",
      "response": "string"
    }}
  ],
  "database_entities": [
    {{
      "name": "string",
      "fields": ["id: UUID PK", "name: VARCHAR(100)"],
      "relationships": ["hasMany: OtherEntity"]
    }}
  ],
  "mermaid_diagram": "graph TD\\n  A[Client] --> B[API Gateway]\\n  ...",
  "key_decisions": [
    "Decision: detailed justification"
  ]
}}

3. Design between 6 and 15 API endpoints coherent with the user stories.
4. Define between 3 and 8 database entities with fields and relationships.
5. The Mermaid diagram must be valid syntax and represent the proposed architecture.
6. Include between 3 and 6 major architectural decisions with their justifications.
7. Choose modern technologies and justify each choice.
8. Do NOT use backticks, do NOT use markdown, ONLY pure JSON.
"""


# ── Retry prompt ─────────────────────────────────────────────────────────────

ARCHITECT_RETRY_PROMPT = """\
Your previous response was NOT a valid JSON. The error was:
{error}

You MUST respond with pure, valid JSON. No extra text, no backticks, no explanations. Only the JSON object that complies with the schema indicated.
Make sure to:
- Escape internal quotes with \"
- Use \\n for line breaks inside strings (especially in mermaid_diagram)
- Do not leave trailing commas at the end of arrays or objects
- Close all braces and brackets correctly

Regenerate the entire response:
"""


# ── Public API ───────────────────────────────────────────────────────────────

def _clean_response(text: str) -> str:
    """Strip markdown code fences and surrounding whitespace."""
    cleaned = re.sub(r"```(?:json)?\s*", "", text)
    cleaned = re.sub(r"```", "", cleaned)
    return cleaned.strip()


def _fix_json(text: str) -> str:
    """Fix common LLM JSON errors: trailing commas before ] or }."""
    fixed = re.sub(r",\s*([}\]])", r"\1", text)
    return fixed


async def enrich_with_context7(tech_stack: TechStack) -> dict:
    """Connect to Context7 MCP and retrieve best practices for the tech stack."""
    from agents.mcp_client import get_mcp_tools, CONTEXT7_MCP_CONFIG

    tools, client = get_mcp_tools(CONTEXT7_MCP_CONFIG, "stdio", return_client=True)
    if not tools:
        print("⚠️ [Context7] Could not load Context7 tools. Fallback.")
        if client:
            client.close()
        return {}

    tool_map = {t.name: t for t in tools}
    docs_found = {}

    technologies = {
        "frontend": tech_stack.frontend,
        "backend": tech_stack.backend,
        "database": tech_stack.database
    }

    try:
        for key, tech_name in technologies.items():
            if not tech_name or tech_name.lower() in ["none", "null", "n/a", "no"]:
                continue

            print(f"🔍 [Context7] Searching ID for library: {tech_name}")
            try:
                resolved_id = None
                if "resolve-library-id" in tool_map:
                    res = await asyncio.to_thread(tool_map["resolve-library-id"].invoke, {
                        "query": tech_name,
                        "libraryName": tech_name
                    })
                    match = re.search(r"(/[a-zA-Z0-9_\-\.]+/[a-zA-Z0-9_\-\.]+)", str(res))
                    if match:
                        resolved_id = match.group(1)
                        print(f"🔍 [Context7] ID resolved for {tech_name}: {resolved_id}")

                if not resolved_id:
                    tech_lower = tech_name.lower()
                    if "nest" in tech_lower:
                        resolved_id = "/nestjs/nest"
                    elif "flutter" in tech_lower:
                        resolved_id = "/flutter/flutter"
                    elif "postgres" in tech_lower:
                        resolved_id = "/postgres/postgres"
                    else:
                        resolved_id = f"/{tech_lower}/{tech_lower}"

                doc_content = ""
                if "query-docs" in tool_map:
                    doc_content = await asyncio.to_thread(tool_map["query-docs"].invoke, {
                        "libraryId": resolved_id,
                        "query": "best practices"
                    })
                elif "get-library-docs" in tool_map:
                    doc_content = await asyncio.to_thread(tool_map["get-library-docs"].invoke, {
                        "libraryId": resolved_id,
                        "topic": "best practices"
                    })

                if doc_content:
                    docs_found[tech_name] = doc_content
                    print(f"✅ [Context7] Best practices retrieved for {tech_name}")
            except Exception as e:
                print(f"⚠️ [Context7] Error searching documentation for {tech_name}: {e}")
    finally:
        if client:
            client.close()

    return docs_found


def _run_async_in_thread(coro):
    """Run an async coroutine synchronously in a separate thread to prevent loop conflicts."""
    q = queue.Queue()
    def worker():
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        try:
            res = loop.run_until_complete(coro)
            q.put((True, res))
        except Exception as e:
            q.put((False, e))
        finally:
            loop.close()
    t = threading.Thread(target=worker, daemon=True)
    t.start()
    t.join()
    success, val = q.get()
    if success:
        return val
    raise val


def refine_architecture_with_docs(arch_output: ArchitectOutput, context7_docs: dict) -> ArchitectOutput:
    """Refine key decisions using documentation from Context7."""
    llm = llm_architect
    
    context7_enriched = False
    if context7_docs:
        context7_enriched = True
        docs_str = json.dumps(context7_docs, indent=2, ensure_ascii=False)
        print("💡 [Architect] Refining decisions with Context7 best practices...")
        refine_prompt = (
            f"Review these architectural decisions in light of current documented best practices:\n{docs_str}\n\n"
            f"Current decisions: {json.dumps(arch_output.key_decisions, indent=2, ensure_ascii=False)}\n\n"
            "Is there anything you would change? Return ONLY a JSON object updating the key_decisions list "
            "with the new insights. Format:\n"
            "{\n"
            "  \"key_decisions\": [\n"
            "    \"Decision: detailed justification\"\n"
            "  ]\n"
            "}"
        )
        try:
            refine_res = llm.invoke([
                SystemMessage(content="You are a Senior Software Architect. Respond strictly with JSON."),
                HumanMessage(content=refine_prompt)
            ])
            refine_data = parse_llm_json(refine_res.content)
            if isinstance(refine_data, dict) and isinstance(refine_data.get("key_decisions"), list):
                arch_output.key_decisions = refine_data["key_decisions"]
                print("✅ [Architect] Decisions successfully updated.")
        except Exception as refine_err:
            print(f"⚠️ [Architect] Error refining decisions with Context7: {refine_err}")

    arch_output.context7_enriched = context7_enriched
    return arch_output


def run_architect_agent(pm_output: PMOutput) -> ArchitectOutput:
    """Send the PM output to the Architect LLM and parse its JSON response."""
    llm = llm_architect

    pm_json = pm_output.model_dump_json(indent=2)
    
    # 1. Normal architect analysis
    messages = [
        SystemMessage(content=ARCHITECT_SYSTEM_PROMPT),
        HumanMessage(
            content=(
                "Analyze the following project document generated by the PM "
                "and propose a complete software architecture:\n\n"
                f"{pm_json}"
            )
        ),
    ]
    
    print("🏗️  Architect Agent generating initial architecture...")
    response = llm.invoke(messages)

    try:
        return ArchitectOutput.model_validate(parse_llm_json(response.content))
    except Exception as exc:
        print(f"   ⚠️ Architecture parsing failed: {exc}. Retrying with direct prompt...")
        try:
            messages = messages + [
                HumanMessage(content=ARCHITECT_RETRY_PROMPT.format(error=str(exc)))
            ]
            retry_res = llm.invoke(messages)
            return ArchitectOutput.model_validate(parse_llm_json(retry_res.content))
        except Exception as retry_exc:
            print(f"   ❌ Architecture retry parsing failed: {retry_exc}")
            raise
