"""QA Agent – Test generator and code reviewer that work in parallel
to produce test cases, test files, and code quality analysis."""

from __future__ import annotations

import json
import os
import re
from typing import Any, Optional

from langchain_core.messages import HumanMessage, SystemMessage
from langgraph.prebuilt import create_react_agent
from pydantic import BaseModel, Field, ValidationError
from config.llm_config import llm_qa
from config.paths import OUTPUT_DIR, ensure_output_dir, safe_join, UnsafePathError
from tools.llm_helpers import parse_llm_json

from agents.pm_agent import PMOutput
from agents.developer_agent import DeveloperOutput
from agents.mcp_client import ThreadSafeMCPClient


# ── Pydantic output models ──────────────────────────────────────────────────

class TestCase(BaseModel):
    id: str = Field(..., description="Unique ID: TC-001, TC-002...")
    user_story_id: str = Field(..., description="Reference to PM user story: US-001...")
    title: str = Field(..., description="Short descriptive title")
    test_type: str = Field(
        ..., description='Type of test: "unit", "integration", or "e2e"'
    )
    preconditions: list[str] = Field(..., description="Preconditions for the test")
    steps: list[str] = Field(..., description="Steps to execute the test")
    expected_result: str = Field(..., description="Expected outcome")
    priority: str = Field(
        default="medium", description='Priority: "critical", "high", "medium", or "low"'
    )


class CodeIssue(BaseModel):
    severity: str = Field(
        ..., description='Severity: "critical", "major", "minor", or "info"'
    )
    file: str = Field(..., description="Affected file path/name")
    description: str = Field(..., description="Description of the issue")
    suggestion: str = Field(..., description="How to fix the issue")
    category: str = Field(
        ...,
        description='Category: "security", "performance", "maintainability", "reliability", or "bug"',
    )


class TestFile(BaseModel):
    filename: str = Field(..., description="Test file name")
    path: str = Field(..., description="Relative path for the test file")
    language: str = Field(..., description="Programming language")
    content: str = Field(..., description="Full test source code")
    description: str = Field(..., description="Brief description of what is tested")


class QAOutput(BaseModel):
    project_name: str = Field(..., description="Project name")
    test_cases: list[TestCase] = Field(..., description="Functional test cases")
    test_files: list[TestFile] = Field(..., description="Generated test code files")
    code_issues: list[CodeIssue] = Field(
        ..., description="Code quality issues found"
    )
    quality_score: int = Field(
        ..., description="Quality score 0-100"
    )
    quality_summary: str = Field(
        ..., description="Executive quality summary"
    )


# ── System prompts ───────────────────────────────────────────────────────────

TEST_GENERATOR_SYSTEM_PROMPT = """\
You are a Senior QA Engineer with over 10 years of experience in mobile \
and backend testing, specializing in Jest (NestJS) and Flutter widget tests.

Your task is to analyze the PM's user stories and the files generated by \
the Developer, and generate:
1. Exhaustive functional test cases (test_cases)
2. Real and functional test code (test_files)

RULES FOR TEST CASES:
- Generate at least 2 TestCase objects for each UserStory of "high" priority, and 1 for others.
- Cover: happy paths, edge cases, and error cases.
- Valid test_type values: "unit", "integration", "e2e"
- Sequential IDs: TC-001, TC-002...
- Each TestCase must reference its corresponding user_story_id (US-001...)

RULES FOR TEST FILES:
- Generate at least 3 test files:
  * A .spec.ts file with Jest unit tests for the most important backend service.
  * A .spec.ts file with integration tests for the main endpoints.
  * A _test.dart file with Flutter widget tests.
- The test code must be real, functional, and executable.

STRICT FORMAT RULES:
1. Respond ONLY with a valid JSON. Do NOT include extra text, comments, or markdown.
2. The JSON must follow EXACTLY this schema:

{{
  "test_cases": [
    {{
      "id": "TC-001",
      "user_story_id": "US-001",
      "title": "string",
      "test_type": "unit | integration | e2e",
      "preconditions": ["string"],
      "steps": ["string"],
      "expected_result": "string",
      "priority": "critical | high | medium | low"
    }}
  ],
  "test_files": [
    {{
      "filename": "expense.service.spec.ts",
      "path": "test",
      "language": "typescript",
      "content": "import {{ Test }} from '@nestjs/testing';\\n...",
      "description": "Unit tests for ExpenseService"
    }}
  ]
}}

3. Correctly escape quotes and line breaks within "content".
4. Do NOT use backticks, do NOT use markdown, ONLY pure JSON.
"""

CODE_REVIEWER_SYSTEM_PROMPT = """\
You are a Senior Code Reviewer with expertise in security, performance, and best \
practices for NestJS (TypeScript) and Flutter (Dart).

Your task is to analyze the code generated by the development team with a \
critical and exhaustive eye.

SEARCH SPECIFICALLY FOR:
- SQL or NoSQL injection
- Missing input validation
- N+1 queries and database performance issues
- Memory leaks
- Missing error handling / try-catch blocks
- Hardcoded secrets or API keys
- SOLID principles violations
- Duplicate code
- Missing types (any, dynamic)
- Missing sanitization of user data
- Endpoints without authentication/authorization
- Missing null checks

RULES FOR QUALITY SCORE:
- Start at 100 and deduct points for each issue found:
  * critical: -15
  * major: -8
  * minor: -3
  * info: -1
- The minimum score is 0.

STRICT FORMAT RULES:
1. Respond ONLY with a valid JSON. Do NOT include extra text, comments, or markdown.
2. The JSON must follow EXACTLY this schema:

{{
  "code_issues": [
    {{
      "severity": "critical | major | minor | info",
      "file": "src/modules/expense/expense.service.ts",
      "description": "string describing the issue",
      "suggestion": "string with how to fix it",
      "category": "security | performance | maintainability | reliability | bug"
    }}
  ],
  "quality_score": 72,
  "quality_summary": "string with executive summary"
}}

3. Be specific: mention the file and the location of the problem when possible.
4. Do NOT use backticks, do NOT use markdown, ONLY pure JSON.
"""

RETRY_PROMPT = """\
Your previous response was NOT valid JSON. The error was:
{error}

You MUST respond with pure and valid JSON. No extra text, no backticks, \
no explanations. Only the JSON object that complies with the indicated schema.
Make sure to:
- Escape internal quotes with \"
- Use \\n for line breaks inside strings
- Do not leave trailing commas in arrays or objects
- Close all braces and brackets correctly

Regenerate the complete response:
"""


# ── Helpers ──────────────────────────────────────────────────────────────────

def _clean_response(text: str) -> str:
    """Strip markdown code fences and surrounding whitespace."""
    cleaned = re.sub(r"```(?:json)?\s*", "", text)
    cleaned = re.sub(r"```", "", cleaned)
    return cleaned.strip()


def _fix_json(text: str) -> str:
    """Fix common LLM JSON errors: trailing commas before ] or }."""
    fixed = re.sub(r",\s*([}\]])", r"\1", text)
    return fixed


def _invoke_with_retry(
    llm: Any,
    messages: list,
    parse_fn,
    max_retries: int = 2,
    label: str = "",
):
    """Invoke the LLM, parse JSON with parse_fn, retry on failure."""
    last_error = None
    for attempt in range(1 + max_retries):
        response = llm.invoke(messages)
        raw_text: str = response.content  # type: ignore[assignment]

        try:
            data = parse_llm_json(raw_text)
            return parse_fn(data)
        except (json.JSONDecodeError, ValidationError, KeyError, TypeError, ValueError) as exc:
            last_error = exc
            print(f"   ⚠️  [{label}] Attempt {attempt + 1} failed: {exc}")
            if attempt < max_retries:
                print(f"   🔄 [{label}] Retrying with stricter prompt...")
                messages = messages + [
                    HumanMessage(content=RETRY_PROMPT.format(error=str(exc)))
                ]

    raise last_error  # type: ignore[misc]


def _summarize_dev_files(dev_output: DeveloperOutput, max_content_chars: int = 500) -> str:
    """Serialize developer files with truncated content to fit context window."""
    summary = {"backend_files": [], "frontend_files": []}

    for f in dev_output.backend.files:
        summary["backend_files"].append({
            "filename": f.filename,
            "path": f.path,
            "language": f.language,
            "description": f.description,
            "content": f.content[:max_content_chars] + ("..." if len(f.content) > max_content_chars else ""),
        })

    for f in dev_output.frontend.files:
        summary["frontend_files"].append({
            "filename": f.filename,
            "path": f.path,
            "language": f.language,
            "description": f.description,
            "content": f.content[:max_content_chars] + ("..." if len(f.content) > max_content_chars else ""),
        })

    return json.dumps(summary, indent=2, ensure_ascii=False)


def _full_dev_code(dev_output: DeveloperOutput) -> str:
    """Serialize all developer code files for deep review."""
    files = []
    for f in dev_output.backend.files + dev_output.frontend.files:
        files.append({
            "filename": f.filename,
            "path": f.path,
            "language": f.language,
            "content": f.content,
        })
    return json.dumps(files, indent=2, ensure_ascii=False)


# ── Public API ───────────────────────────────────────────────────────────────

async def run_e2e_tests(developer_output: DeveloperOutput) -> dict:
    """Connect to Playwright MCP and perform basic E2E verification or simulate via HTTP."""
    from agents.mcp_client import get_mcp_tools, PLAYWRIGHT_MCP_CONFIG
    import aiohttp

    # 1. Detect URLs or endpoints. Base URL/port is derived from the environment so
    #    it is not hardcoded to localhost:3000.
    base_url = os.getenv("E2E_BASE_URL", "http://localhost:3000").rstrip("/")
    urls_to_test = [base_url]

    def _join_route(prefix: str, path: str) -> str:
        prefix = (prefix or "").strip("/")
        path = (path or "").strip("/")
        segments = [seg for seg in (prefix, path) if seg]
        return "/".join(segments)

    for f in developer_output.backend.files:
        # Pick up the @Controller('prefix') so routes are rooted correctly.
        controller_match = re.search(r"@Controller\(\s*['\"]([^'\"]*)['\"]", f.content)
        controller_prefix = controller_match.group(1) if controller_match else ""

        # Parse GET/POST/PUT/DELETE route decorators.
        route_paths = re.findall(
            r"@(?:Get|Post|Put|Delete|Patch)\(\s*['\"]([^'\"]+)['\"]\s*\)",
            f.content,
        )
        # Decorators with no explicit path map to the controller root.
        if re.search(r"@(?:Get|Post|Put|Delete|Patch)\(\s*\)", f.content):
            route_paths.append("")

        for p in route_paths:
            if p.startswith("http"):
                continue
            full_route = _join_route(controller_prefix, p)
            url = f"{base_url}/{full_route}" if full_route else base_url
            if url not in urls_to_test:
                urls_to_test.append(url)

    print(f"🕵️  [QA E2E] Endpoints detected to test: {urls_to_test}")

    # 2. Connect to Playwright MCP
    tools, mcp_client = get_mcp_tools(PLAYWRIGHT_MCP_CONFIG, "stdio", return_client=True)
    tool_map = {t.name: t for t in tools} if tools else {}

    e2e_results = {}

    import asyncio

    tests_dir = ensure_output_dir() / "tests"
    tests_dir.mkdir(parents=True, exist_ok=True)

    try:
        if "playwright_navigate" in tool_map and "playwright_screenshot" in tool_map:
            print("🎭 [QA E2E] Playwright MCP available. Starting E2E tests...")
            for url in urls_to_test:
                try:
                    print(f"🌐 Navigating to: {url}")
                    nav_res = await asyncio.to_thread(
                        tool_map["playwright_navigate"].invoke, {"url": url}
                    )
                    screenshot_name = f"screenshot_{re.sub(r'[^a-zA-Z0-9]', '_', url)}.png"
                    screenshot_path = str(tests_dir / screenshot_name)

                    await asyncio.to_thread(
                        tool_map["playwright_screenshot"].invoke,
                        {"path": screenshot_path},
                    )
                    e2e_results[url] = {
                        "status": "success",
                        "screenshot_path": screenshot_path,
                        "info": str(nav_res)
                    }
                except Exception as e:
                    print(f"⚠️ Error navigating/capturing {url}: {e}")
                    e2e_results[url] = {
                        "status": "error",
                        "error": str(e)
                    }
        else:
            print("⚠️ [QA E2E] Playwright MCP not available. Using fallback with aiohttp...")
            async with aiohttp.ClientSession() as session:
                for url in urls_to_test:
                    try:
                        print(f"🔗 Performing GET (aiohttp) to: {url}")
                        timeout = aiohttp.ClientTimeout(total=5)
                        async with session.get(url, timeout=timeout) as response:
                            e2e_results[url] = {
                                "status": "simulated",
                                "http_code": response.status,
                                "reason": response.reason,
                                "screenshot_path": "not available (simulated)"
                            }
                    except Exception as e:
                        error_msg = str(e)
                        status_name = "simulated_error"
                        # Check if the connection failed because the local server is offline
                        if "connection refused" in error_msg.lower() or "cannot connect to host" in error_msg.lower() or "timeout" in error_msg.lower():
                            status_name = "server_offline"

                        e2e_results[url] = {
                            "status": status_name,
                            "error": error_msg,
                            "screenshot_path": "not available (simulated)"
                        }
    finally:
        if mcp_client:
            mcp_client.close()

    return e2e_results


async def generate_test_files_with_filesystem(test_files: list[TestFile]):
    """Save QA test files to ./output/tests/ using Filesystem MCP or Python fallback."""
    from agents.mcp_client import get_mcp_tools, FILESYSTEM_MCP_CONFIG

    tools, mcp_client = get_mcp_tools(FILESYSTEM_MCP_CONFIG, "stdio", return_client=True)
    tool_map = {t.name: t for t in tools} if tools else {}

    test_dir = ensure_output_dir() / "tests"
    test_dir.mkdir(parents=True, exist_ok=True)

    mcp_available = "write_file" in tool_map

    try:
        for f in test_files:
            # Validate the LLM-supplied filename so it cannot escape the test dir.
            try:
                safe_path = safe_join(test_dir, f.filename)
            except UnsafePathError as ue:
                print(f"⚠️ [QA] Skipping test file with unsafe name {f.filename!r}: {ue}")
                continue

            rel_path = os.path.join("tests", f.filename)

            if mcp_available:
                try:
                    safe_path.parent.mkdir(parents=True, exist_ok=True)
                    print(f"🚀 [Filesystem MCP] Saving test file: {rel_path}...")
                    tool_map["write_file"].invoke({
                        "path": str(safe_path),
                        "content": f.content
                    })
                    print(f"📄 Saved test: {rel_path}")
                    continue
                except Exception as e:
                    print(f"⚠️ [Filesystem MCP] Error writing test {rel_path}: {e}. Local fallback...")

            try:
                safe_path.parent.mkdir(parents=True, exist_ok=True)
                with open(safe_path, "w", encoding="utf-8") as out_f:
                    out_f.write(f.content)
                print(f"📄 Saved test (Local Fallback): {safe_path}")
            except Exception as e:
                print(f"❌ Error writing local test file: {e}")
    finally:
        if mcp_client:
            mcp_client.close()


def run_test_generator(
    pm_output: PMOutput, developer_output: DeveloperOutput
) -> dict:
    """Generate test cases and test files from PM stories + Developer files, using Playwright if needed."""
    
    # Connect Playwright MCP
    playwright_client = ThreadSafeMCPClient("npx", ["-y", "@playwright/mcp@latest"])
    try:
        tools = playwright_client.get_tools()

        llm = llm_qa

        agent = create_react_agent(llm, tools=tools)

        stories_json = json.dumps(
            [s.model_dump() for s in pm_output.user_stories],
            indent=2,
            ensure_ascii=False,
        )
        dev_summary = _summarize_dev_files(developer_output)

        prompt = (
            f"{TEST_GENERATOR_SYSTEM_PROMPT}\n\n"
            "Generate test cases and test code based on these user stories and Developer files. "
            "If you need to validate or interact with a browser to generate/verify UI flows, use the Playwright tools:\n\n"
            f"USER STORIES:\n{stories_json}\n\n"
            f"DEVELOPER FILES:\n{dev_summary}"
        )

        print("🧪  QA Agent (Test Generator) consulting tools and generating tests...")
        response = agent.invoke(
            {"messages": [HumanMessage(content=prompt)]},
            config={"recursion_limit": 100},
        )

        # Guard: only parse JSON from an AI message, not a trailing tool message.
        messages_list = response["messages"]
        final_message = ""
        for msg in reversed(messages_list):
            if getattr(msg, "type", None) == "ai" and msg.content:
                final_message = msg.content
                break
        if not final_message and messages_list:
            last_msg = messages_list[-1]
            if getattr(last_msg, "type", None) == "ai":
                final_message = last_msg.content

        try:
            data = parse_llm_json(final_message)
            test_cases = [TestCase.model_validate(tc) for tc in data.get("test_cases", [])]
            test_files = [TestFile.model_validate(tf) for tf in data.get("test_files", [])]
            return {"test_cases": test_cases, "test_files": test_files}
        except Exception as exc:
            print(f"   ⚠️ Test parsing failed: {exc}. Retrying with direct prompt...")
            try:
                messages = [
                    SystemMessage(content=TEST_GENERATOR_SYSTEM_PROMPT),
                    HumanMessage(content=prompt),
                    HumanMessage(content=RETRY_PROMPT.format(error=str(exc)))
                ]
                retry_res = llm.invoke(messages)
                data = parse_llm_json(retry_res.content)
                test_cases = [TestCase.model_validate(tc) for tc in data.get("test_cases", [])]
                test_files = [TestFile.model_validate(tf) for tf in data.get("test_files", [])]
                return {"test_cases": test_cases, "test_files": test_files}
            except Exception as retry_exc:
                print(f"   ❌ Test retry parsing failed: {retry_exc}. Returning empty test set.")
                return {"test_cases": [], "test_files": []}
    finally:
        playwright_client.close()


def run_code_reviewer(developer_output: DeveloperOutput) -> dict:
    """Review developer code for quality issues."""
    llm = llm_qa

    code_json = _full_dev_code(developer_output)

    messages = [
        SystemMessage(content=CODE_REVIEWER_SYSTEM_PROMPT),
        HumanMessage(
            content=(
                "Analyze the following code generated by the development team "
                "and report all the quality issues you find:\n\n"
                f"{code_json}"
            )
        ),
    ]

    def parse_review_output(data: dict) -> dict:
        code_issues = [CodeIssue.model_validate(ci) for ci in data.get("code_issues", [])]
        # Coerce defensively: the LLM may emit a non-numeric value like "N/A".
        try:
            quality_score = max(0, min(100, int(data.get("quality_score", 0))))
        except (ValueError, TypeError):
            quality_score = 0
        quality_summary = str(data.get("quality_summary", ""))
        return {
            "code_issues": code_issues,
            "quality_score": quality_score,
            "quality_summary": quality_summary,
        }

    return _invoke_with_retry(llm, messages, parse_review_output, label="CodeReview")


def merge_qa_outputs(
    project_name: str,
    test_output: dict,
    review_output: dict,
) -> QAOutput:
    """Combine test generator and code reviewer outputs into a QAOutput."""
    return QAOutput(
        project_name=project_name,
        test_cases=test_output["test_cases"],
        test_files=test_output["test_files"],
        code_issues=review_output["code_issues"],
        quality_score=review_output["quality_score"],
        quality_summary=review_output["quality_summary"],
    )
