"""Reviewer Agent – Human-in-the-loop code reviewer."""

from __future__ import annotations

import json
import re
from typing import Optional, Any

from langchain_core.messages import HumanMessage, SystemMessage
from pydantic import BaseModel, Field
from config.llm_config import llm_reviewer
from tools.llm_helpers import clean_llm_response

from agents.developer_agent import DeveloperOutput
from agents.qa_agent import QAOutput


# ── Pydantic models ──────────────────────────────────────────────────────────

class CodeChange(BaseModel):
    file: str = Field(..., description="File to modify")
    original_snippet: str = Field(..., description="Original code snippet (max 10 lines)")
    proposed_snippet: str = Field(..., description="Proposed code snippet")
    reason: str = Field(..., description="Justification for the change")
    change_type: str = Field(
        ..., description='Type: "refactor", "bugfix", "security", "performance", or "style"'
    )


class ReviewComment(BaseModel):
    file: str = Field(..., description="File path")
    line_reference: str = Field(..., description='E.g. "línea 42" or "líneas 10-15"')
    severity: str = Field(
        ..., description='Severity: "blocking", "important", or "suggestion"'
    )
    comment: str = Field(..., description="Review comment text")
    change: Optional[CodeChange] = Field(default=None, description="Proposed code change")


class ReviewRound(BaseModel):
    round_number: int = Field(..., description="Round number (starts at 1)")
    comments: list[ReviewComment] = Field(..., description="List of review comments")
    blocking_count: int = Field(..., description="Number of blocking comments")
    important_count: int = Field(..., description="Number of important comments")
    suggestion_count: int = Field(..., description="Number of suggestion comments")
    overall_verdict: str = Field(
        ..., description='"approved", "approved_with_suggestions", or "changes_required"'
    )
    verdict_reason: str = Field(..., description="Brief reason for the verdict")
    think_content: Optional[str] = Field(default=None, description="Reasoning block from the LLM")


class HumanDecision(BaseModel):
    approved: bool = Field(..., description="Whether the human approved the round")
    feedback: str = Field(..., description="Human feedback/comment")
    timestamp: str = Field(..., description="Timestamp of the decision")


class ReviewerOutput(BaseModel):
    project_name: str = Field(..., description="Project name")
    rounds: list[ReviewRound] = Field(..., description="History of all rounds")
    human_decisions: list[HumanDecision] = Field(..., description="History of human decisions")
    final_status: str = Field(
        ..., description='"approved", "approved_with_suggestions", or "rejected"'
    )
    total_changes_proposed: int = Field(..., description="Total changes proposed")
    approved_changes: list[CodeChange] = Field(..., description="Changes that were approved")


# ── System prompts ───────────────────────────────────────────────────────────

REVIEWER_SYSTEM_PROMPT = """\
You are the Lead Code Reviewer (Tech Lead) of the team. Your mission is to ensure \
that the generated code meets the strictest standards before going \
into production. You are meticulous, direct, and justify every comment.

You have at your disposal:
1. The code generated by the developers.
2. The quality issues already detected by the QA Agent.
3. The history of previous code review rounds and human feedback.

REVIEW RULES:
- DO NOT repeat issues already detected by the QA Agent, assume those will be fixed. \
  Focus on architecture, deep maintainability, business logic, and more \
  subtle bugs.
- Propose concrete code snippets in "original_snippet" and "proposed_snippet" \
  when suggesting a change.
- If the human gives you feedback or rejects the previous round, you MUST incorporate \
  that feedback in this new round and adjust your verdict.
- overall_verdict must be "approved", "approved_with_suggestions", or "changes_required".

STRICT FORMAT RULES:
1. Respond ONLY with a valid JSON. Do NOT include extra text, comments, or markdown.
2. The JSON must follow EXACTLY this schema (for the ReviewRound class):

{{
  "round_number": 1,
  "comments": [
    {{
      "file": "src/app.module.ts",
      "line_reference": "lines 10-15",
      "severity": "blocking | important | suggestion",
      "comment": "string",
      "change": {{
        "file": "src/app.module.ts",
        "original_snippet": "string",
        "proposed_snippet": "string",
        "reason": "string",
        "change_type": "refactor | bugfix | security | performance | style"
      }}
    }}
  ],
  "blocking_count": 1,
  "important_count": 0,
  "suggestion_count": 0,
  "overall_verdict": "changes_required | approved_with_suggestions | approved",
  "verdict_reason": "string"
}}

3. Correctly escape quotes and line breaks within "comment" and "snippet".
4. Do NOT use backticks, do NOT use markdown, ONLY pure JSON.
"""

RETRY_PROMPT = """\
Your previous response was NOT valid JSON. The error was:
{error}

You MUST respond with pure and valid JSON. No extra text, no backticks, \
no explanations. Only the JSON object that complies with the indicated schema.
Make sure to:
- Escape internal quotes with \"
- Use \\n for line breaks inside strings
- Do not leave trailing commas in arrays or objects
- Close all braces and brackets correctly

Regenerate the complete response:
"""


# ── Helpers ──────────────────────────────────────────────────────────────────

def _clean_response(text: str) -> str:
    cleaned = re.sub(r"```(?:json)?\s*", "", text)
    cleaned = re.sub(r"```", "", cleaned)
    return cleaned.strip()


def _parse_json_robust(text: str) -> dict:
    from json_repair import loads as repair_loads
    try:
        return json.loads(text, strict=False)
    except json.JSONDecodeError:
        return repair_loads(text)


def _invoke_with_retry(
    llm: Any,
    messages: list,
    parse_fn,
    max_retries: int = 2,
    label: str = "",
):
    last_error = None
    for attempt in range(1 + max_retries):
        response = llm.invoke(messages)
        raw_text: str = response.content  # type: ignore[assignment]
        cleaned = clean_llm_response(raw_text)

        # Extract <think> block if present
        think_match = re.search(r'<think>(.*?)</think>', raw_text, re.DOTALL)
        think_content = think_match.group(1).strip() if think_match else None

        try:
            data = _parse_json_robust(cleaned)
            result = parse_fn(data)
            if think_content and hasattr(result, 'think_content'):
                result.think_content = think_content
            return result
        except Exception as exc:
            last_error = exc
            print(f"   ⚠️  [{label}] Attempt {attempt + 1} failed: {exc}")
            if attempt < max_retries:
                print(f"   🔄 [{label}] Retrying with stricter prompt...")
                messages = messages + [
                    HumanMessage(content=RETRY_PROMPT.format(error=str(exc)))
                ]

    raise last_error  # type: ignore[misc]


def _coerce_to_obj(result: Any) -> Any:
    """Best-effort coercion of an MCP tool result (often a string or JSON-RPC
    content envelope) into a Python dict/list for structured extraction."""
    if isinstance(result, (dict, list)):
        return result
    if isinstance(result, str):
        try:
            return _parse_json_robust(clean_llm_response(result))
        except Exception:
            return result
    return result


def _extract_sha(result: Any) -> Optional[str]:
    """Pull a file blob ``sha`` out of a get-file-contents MCP tool result."""
    obj = _coerce_to_obj(result)
    if isinstance(obj, dict):
        if isinstance(obj.get("sha"), str):
            return obj["sha"]
        # Some servers nest the file under "content" or "result".
        for key in ("content", "result", "data"):
            nested = obj.get(key)
            if isinstance(nested, dict) and isinstance(nested.get("sha"), str):
                return nested["sha"]
    return None


def _parse_pr_result(result: Any) -> tuple[Optional[str], Optional[int]]:
    """Parse the PR URL and number from a create_pull_request MCP tool result.

    Prefers structured fields (html_url / number); falls back to a regex over the
    serialized result so we never invent a bogus ``/pull/new`` link.
    """
    obj = _coerce_to_obj(result)
    url: Optional[str] = None
    number: Optional[int] = None
    if isinstance(obj, dict):
        for key in ("html_url", "url", "pr_url"):
            if isinstance(obj.get(key), str) and "/pull/" in obj[key]:
                url = obj[key]
                break
        if isinstance(obj.get("number"), int):
            number = obj["number"]

    text = str(result)
    if url is None:
        m = re.search(r'(https://github\.com/[^\s"\']+/pull/\d+)', text)
        if m:
            url = m.group(1)
    if number is None and url:
        m = re.search(r'/pull/(\d+)', url)
        if m:
            number = int(m.group(1))
    return url, number


def _summarize_dev_files(dev_output: DeveloperOutput, max_chars: int = 800) -> str:
    summary = []
    for f in dev_output.backend.files + dev_output.frontend.files:
        content = f.content[:max_chars] + ("..." if len(f.content) > max_chars else "")
        summary.append({"filename": f.filename, "content": content})
    return json.dumps(summary, indent=2, ensure_ascii=False)


# ── Public API ───────────────────────────────────────────────────────────────

def run_reviewer(
    developer_output: DeveloperOutput,
    qa_output: QAOutput,
    previous_rounds: list[ReviewRound],
    human_feedback: Optional[str],
) -> ReviewRound:
    """Run the Code Reviewer agent."""
    llm = llm_reviewer

    dev_summary = _summarize_dev_files(developer_output)
    
    qa_issues = [
        {"file": issue.file, "description": issue.description, "severity": issue.severity}
        for issue in qa_output.code_issues
    ]
    qa_summary = json.dumps(qa_issues, indent=2, ensure_ascii=False)

    history_msg = ""
    if previous_rounds:
        for r in previous_rounds:
            history_msg += f"\n--- Round {r.round_number} ---\n"
            history_msg += f"Verdict: {r.overall_verdict} - {r.verdict_reason}\n"
            for c in r.comments:
                history_msg += f"[{c.severity}] {c.file}: {c.comment}\n"
    
    feedback_msg = ""
    if human_feedback:
        feedback_msg = f"\nHUMAN FEEDBACK FOR THIS ROUND:\n{human_feedback}\n"
    
    current_round_num = len(previous_rounds) + 1
 
    prompt_content = f"""
DEVELOPER FILES:
{dev_summary}

QA AGENT ISSUES (ALREADY DETECTED, DO NOT REPEAT):
{qa_summary}
"""

    if history_msg:
        prompt_content += f"\nHISTORY OF PREVIOUS ROUNDS:{history_msg}"
    
    if feedback_msg:
        prompt_content += feedback_msg
    
    prompt_content += f"\nGenerate the code review for ROUND {current_round_num}."

    messages = [
        SystemMessage(content=REVIEWER_SYSTEM_PROMPT),
        HumanMessage(content=prompt_content),
    ]

    def parse_output(data: dict) -> ReviewRound:
        data["round_number"] = current_round_num
        return ReviewRound.model_validate(data)

    return _invoke_with_retry(llm, messages, parse_output, label="CodeReviewer")


async def create_github_pr(reviewer_output: ReviewerOutput, developer_output: DeveloperOutput) -> dict:
    """Connect to GitHub MCP, create a branch, push review refinements, and open a Pull Request."""
    from agents.mcp_client import get_mcp_tools, GITHUB_MCP_CONFIG
    import asyncio
    import os
    import time

    owner = os.getenv("GITHUB_OWNER")
    repo = os.getenv("GITHUB_OUTPUT_REPO") or os.getenv("GITHUB_PROJECT_REPO")
    if not repo:
        proj_clean = developer_output.project_name.lower().replace(" ", "-").replace("_", "-")
        print("⚠️  [GitHub] GITHUB_OUTPUT_REPO is not set in your .env file.")
        print(f"   -> Defaulting dynamically to repository name: '{proj_clean}'. Make sure you have created this repository on GitHub!")
        repo = proj_clean

    # Abort gracefully if we don't know who owns the target repo.
    if not owner:
        print("⚠️  [GitHub] GITHUB_OWNER is not set; cannot determine target repository owner.")
        return {
            "status": "aborted",
            "pr_url": None,
            "branch": None,
            "reason": "GITHUB_OWNER environment variable is not set.",
        }

    def _normalize(path: str) -> str:
        return os.path.normpath((path or "").strip().lstrip("/"))

    def _resolve_file_content(change) -> str:
        """Resolve the full updated content for a change by matching the dev file
        on full normalized path equality (path/filename), not substring."""
        target = _normalize(change.file)
        matched_content = None
        for dev_file in developer_output.backend.files + developer_output.frontend.files:
            dev_full = _normalize(os.path.join(dev_file.path, dev_file.filename))
            if dev_full == target:
                matched_content = dev_file.content
                break

        if matched_content is not None:
            if change.original_snippet and change.proposed_snippet:
                return matched_content.replace(change.original_snippet, change.proposed_snippet)
            return matched_content
        # No matching dev file: fall back to the proposed snippet as the new content.
        return change.proposed_snippet or ""

    # 1. Connect to GitHub MCP
    tools, mcp_client = get_mcp_tools(GITHUB_MCP_CONFIG, "stdio", return_client=True)
    tool_map = {t.name: t for t in tools} if tools else {}

    # Check if tools are present and valid
    github_available = all(k in tool_map for k in ["create_branch", "create_or_update_file", "create_pull_request"])
    get_file_tool = next(
        (tool_map[k] for k in ("get_file_contents", "get_file", "get_contents") if k in tool_map),
        None,
    )

    branch_name = f"review-refinements-{int(time.time())}"

    try:
        if github_available:
            try:
                print(f"🐙 [GitHub MCP] Starting creation of branch '{branch_name}' in {owner}/{repo}...")
                create_branch_res = await asyncio.to_thread(tool_map["create_branch"].invoke, {
                    "owner": owner,
                    "repo": repo,
                    "branch": branch_name,
                    "base_branch": "main"
                })
                print(f"✅ Branch '{branch_name}' created: {create_branch_res}")

                # Push changed files
                for change in reviewer_output.approved_changes:
                    file_content = _resolve_file_content(change)
                    if not file_content:
                        print(f"⚠️ [GitHub MCP] No content resolved for {change.file}; skipping.")
                        continue

                    update_args = {
                        "owner": owner,
                        "repo": repo,
                        "path": change.file,
                        "message": f"Apply review refinements for {change.file}: {change.reason}",
                        "content": file_content,
                        "branch": branch_name
                    }

                    # If the file already exists, GitHub requires its blob sha to update it.
                    if get_file_tool is not None:
                        try:
                            existing = await asyncio.to_thread(get_file_tool.invoke, {
                                "owner": owner,
                                "repo": repo,
                                "path": change.file,
                                "ref": branch_name,
                            })
                            sha = _extract_sha(existing)
                            if sha:
                                update_args["sha"] = sha
                        except Exception as sha_err:
                            print(f"   ℹ️ [GitHub MCP] Could not fetch existing sha for {change.file} (treating as new): {sha_err}")

                    print(f"🚀 [GitHub MCP] Updating file {change.file} on branch {branch_name}...")
                    await asyncio.to_thread(tool_map["create_or_update_file"].invoke, update_args)

                # Create Pull Request
                pr_body = (
                    f"# Review Refinements - AI Dev Team\n\n"
                    f"This Pull Request contains automatic changes proposed by the Code Reviewer Agent "
                    f"and approved by the human in the final round.\n\n"
                    f"## Summary of changes:\n"
                )
                for c in reviewer_output.approved_changes:
                    pr_body += f"- **{c.file}**: {c.reason} ({c.change_type})\n"

                print(f"🐙 [GitHub MCP] Opening Pull Request for branch '{branch_name}'...")
                pr_res = await asyncio.to_thread(tool_map["create_pull_request"].invoke, {
                    "owner": owner,
                    "repo": repo,
                    "title": f"Review Refinements - AI Dev Team ({branch_name})",
                    "body": pr_body,
                    "head": branch_name,
                    "base": "main"
                })

                pr_url, pr_number = _parse_pr_result(pr_res)
                if not pr_url:
                    # Fall back to the compare view rather than a misleading /pull/new link.
                    pr_url = f"https://github.com/{owner}/{repo}/compare/main...{branch_name}"

                print(f"✅ Pull Request successfully created: {pr_url}")
                return {
                    "status": "success",
                    "pr_url": pr_url,
                    "pr_number": pr_number,
                    "branch": branch_name,
                    "info": str(pr_res)
                }

            except Exception as e:
                print(f"⚠️ [GitHub MCP] GitHub flow failed: {e}. Using simulated fallback...")

        # Fallback / Simulated
        print("⚠️ [GitHub PR] GitHub MCP not available or connection failed. Simulating PR creation locally.")
        simulated_pr_url = f"https://github.com/{owner}/{repo}/compare/main...{branch_name}"
        return {
            "status": "simulated",
            "pr_url": simulated_pr_url,
            "branch": branch_name,
            "reason": "GitHub MCP not available or without credentials, PR was simulated locally."
        }
    finally:
        if mcp_client:
            mcp_client.close()
