from typing import List
from pydantic import BaseModel, Field
from config.llm_config import llm_designer
from tools.llm_helpers import parse_llm_json
from langchain_core.messages import SystemMessage, HumanMessage
from langgraph.prebuilt import create_react_agent

from agents.architect_agent import ArchitectOutput
from agents.stitch_mcp import StitchMCPClient
import json_repair

# ── Pydantic Models ────────────────────────────────────────────────────────────

class UIScreen(BaseModel):
    """Represents a generated UI screen."""
    name: str = Field(..., description="Name of the screen, e.g., 'Home', 'Dashboard'")
    description: str = Field(..., description="Description of the screen and its components")
    stitch_screen_url: str = Field(default="", description="The URL or resource name generated by Google Stitch")
    html_content: str = Field(default="", description="HTML content representation of the screen")

class UIDesignerOutput(BaseModel):
    """The final output from the UI Designer Agent."""
    project_name: str = Field(..., description="Name of the UI project")
    design_system_notes: str = Field(..., description="Notes on the generated design system (colors, typography, etc.)")
    screens: List[UIScreen] = Field(default_factory=list, description="List of generated UI screens")

# ── Prompts ────────────────────────────────────────────────────────────────────

UIDESIGNER_SYSTEM_PROMPT = """You are the UI Designer Agent of the development team.
Your job is to use the Google Stitch tools (available via functions) to generate the screens and the design system of the project based on the proposed architecture.

PROCESS TO FOLLOW:
1. Create a new project in Google Stitch (create_project) or use an existing one.
2. Generate the design system (create_design_system_from_design_md or another).
3. For each view required in the frontend of the architecture, use 'generate_screen_from_text' or 'create_screen' to build the UI.
4. When you have finished generating the screens, you MUST generate your final output by returning ONLY a structured JSON object that conforms to this format:

```json
{
  "project_name": "Name",
  "design_system_notes": "...",
  "screens": [
    {
      "name": "Home",
      "description": "...",
      "stitch_screen_url": "projects/XYZ/screens/123"
    }
  ]
}
```
Do not include any text outside the final JSON."""

from typing import Any

def _extract_nested_json(data: Any) -> Any:
    """Helper to extract nested JSON string if the parsed output is wrapped in a JSON-RPC / content envelope."""
    # Handle double-serialized or double-escaped strings
    if isinstance(data, str):
        data_stripped = data.strip()
        if data_stripped.startswith("{") or data_stripped.startswith("["):
            try:
                data = parse_llm_json(data_stripped)
            except Exception:
                pass

    if isinstance(data, dict):
        if "result" in data:
            return _extract_nested_json(data["result"])
        if "content" in data and isinstance(data["content"], list) and len(data["content"]) > 0:
            first_block = data["content"][0]
            if isinstance(first_block, dict) and "text" in first_block:
                text_content = first_block["text"]
                try:
                    inner_data = parse_llm_json(text_content)
                    return _extract_nested_json(inner_data)
                except Exception:
                    pass
    return data

# ── Public API ─────────────────────────────────────────────────────────────────

def _extract_screens_from_history(messages: List[Any]) -> List[UIScreen]:
    screens: List[UIScreen] = []
    seen_urls = set()

    def scan_obj(obj: Any):
        if isinstance(obj, list):
            for item in obj:
                scan_obj(item)
        elif isinstance(obj, dict):
            # Check if it matches a Stitch API screen structure with a screenshot
            if "screenshot" in obj and isinstance(obj["screenshot"], dict):
                url = obj["screenshot"].get("name") or obj["screenshot"].get("url") or ""
                screen_name = obj.get("name") or obj.get("title") or obj["screenshot"].get("title") or "Unnamed Screen"
                description = obj.get("description") or obj.get("prompt") or ""
                html_content = obj.get("html") or obj.get("html_content") or ""
                if url and url not in seen_urls:
                    seen_urls.add(url)
                    screens.append(UIScreen(
                        name=screen_name,
                        description=description,
                        stitch_screen_url=url,
                        html_content=html_content
                    ))
            # Also check if it matches a standard UIScreen structure (perhaps returned by the agent)
            elif ("stitch_screen_url" in obj or "stitchScreenUrl" in obj) and (obj.get("stitch_screen_url") or obj.get("stitchScreenUrl")):
                url = obj.get("stitch_screen_url") or obj.get("stitchScreenUrl") or ""
                screen_name = obj.get("name") or obj.get("title") or "Unnamed Screen"
                description = obj.get("description") or ""
                html_content = obj.get("html_content") or obj.get("html") or ""
                if url and url not in seen_urls:
                    seen_urls.add(url)
                    screens.append(UIScreen(
                        name=screen_name,
                        description=description,
                        stitch_screen_url=url,
                        html_content=html_content
                    ))
            
            # Recurse into all keys to find nested screens
            for k, v in obj.items():
                scan_obj(v)

    for msg in messages:
        content = getattr(msg, "content", "")
        if not isinstance(content, str) or not content.strip():
            continue
            
        content_stripped = content.strip()
        start_idx = 0
        while True:
            first_brace = content_stripped.find("{", start_idx)
            first_bracket = content_stripped.find("[", start_idx)
            
            if first_brace == -1 and first_bracket == -1:
                break
                
            if first_brace != -1 and (first_bracket == -1 or first_brace < first_bracket):
                start = first_brace
            else:
                start = first_bracket
                
            try:
                parsed = json_repair.loads(content_stripped[start:])
                scan_obj(parsed)
            except Exception:
                pass
                
            start_idx = start + 1
            if start_idx >= len(content_stripped):
                break

    return screens

def run_ui_designer_agent(architect_output: ArchitectOutput, stitch_api_key: str) -> UIDesignerOutput:
    """Uses Google Stitch to design UI screens based on the architecture."""
    
    # Initialize Stitch MCP Tools
    stitch_client = StitchMCPClient(api_key=stitch_api_key)
    try:
        try:
            tools = stitch_client.get_tools()
            print(f"🔧 [UIDesigner] Loaded {len(tools)} Google Stitch tools.")
        except Exception as e:
            print(f"⚠️ [UIDesigner] Error loading Stitch tools: {e}. Running without tools.")
            tools = []

        llm = llm_designer

        agent = create_react_agent(llm, tools=tools)

        arch_json = architect_output.model_dump_json(indent=2)

        # Combine the system prompt with the human message as the first prompt
        prompt = f"{UIDESIGNER_SYSTEM_PROMPT}\n\nHere is the system architecture:\n{arch_json}\n\nUse Stitch tools to generate the screens, and then return the structured JSON."

        print("🎨 [UIDesigner] Generating screens with Google Stitch...")
        response = agent.invoke({"messages": [HumanMessage(content=prompt)]}, config={"recursion_limit": 100})

        # Search backwards for the last AIMessage to get the LLM's final structured text
        final_message = ""
        messages_list = response.get("messages", []) if isinstance(response, dict) else getattr(response, "messages", [])

        for msg in reversed(messages_list):
            if getattr(msg, "type", None) == "ai" and msg.content:
                final_message = msg.content
                break

        if not final_message and messages_list:
            # Guard: only treat the last message as JSON if it is an AI message,
            # not a tool result message.
            last_msg = messages_list[-1]
            if getattr(last_msg, "type", None) == "ai":
                final_message = last_msg.content
    finally:
        stitch_client.close()

    # Parse the final JSON from the agent's last message
    parsed_output = None
    try:
        data = _extract_nested_json(parse_llm_json(final_message))
        if isinstance(data, dict):
            parsed_output = UIDesignerOutput.model_validate(data)
        else:
            raise ValueError("Parsed UI Designer output is not a dictionary.")
    except Exception as e:
        print(f"⚠️ [UIDesigner] Error parsing JSON output: {e}")

    # Extract all screens created in the tools history
    history_screens = _extract_screens_from_history(messages_list)
    print(f"🎨 [UIDesigner] Found {len(history_screens)} screens designed in execution history.")
    
    if parsed_output:
        # Merge screens from history and parsed_output based on stitch_screen_url
        existing_urls = {s.stitch_screen_url for s in parsed_output.screens if s.stitch_screen_url}
        for h_scr in history_screens:
            if h_scr.stitch_screen_url not in existing_urls:
                parsed_output.screens.append(h_scr)
                existing_urls.add(h_scr.stitch_screen_url)
        return parsed_output
    else:
        # Reconstruct UIDesignerOutput completely from history
        print(f"🔄 [UIDesigner] Reconstructed screens from execution history.")
        return UIDesignerOutput(
            project_name=architect_output.project_name,
            design_system_notes="Reconstructed from tools execution history.",
            screens=history_screens
        )
